### PR TITLE
Adobrev/redesign

### PR DESCRIPTION
**Pull request by AntonDobrev**

### CODE REVIEW

**Comment by didiepetrova** [comment]
Cordova version should be updated.
ReadMe.md to be updated in accordance to the latest doc, also the path to the screenshot.

**Comment by TsvetinaIvanova** [comment]
Seems like you didn't update the Cordova version (see the js files).

**Comment by AntonDobrev** [comment]
All feedback and requirements are incorporated now.

**Comment by TsvetinaIvanova** [comment]
:+1:

**Comment by didiepetrova** [comment]
:+1:

**Pull request merged**
